Style/Documentation:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Style/MethodMissing:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
AllCops:
  Exclude:
    - tests
  TargetRubyVersion: '2.4'
